[jenkins_master]
i-0410d02b3785cf70c

[jenkins_master:vars]
ansible_ssh_private_key_file=~/.ssh/jenkins-ansible-key.pem

[jenkins_agent]
i-04b38b0c0c2ac03f3

[jenkins_agent:vars]
ansible_ssh_private_key_file=~/.ssh/jenkins-ansible-key.pem